# config/packages/security.yaml
security:

    # ---------------- PASSWORD HASH ----------------
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto' # hash auto

    # ---------------- USER PROVIDER ----------------
    providers:
        app_user_provider:  # chercher users dans la BDD
            entity:
                class: App\Entity\User
                property: email

    # ---------------- FIREWALLS ----------------
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false  # pas de sécurité pour dev tools et assets

        main:
            lazy: true
            provider: app_user_provider

            # login via formulaire
            form_login:
                login_path: login      # route page login
                check_path: login      # route submit form
                default_target_path: / # après login redirige accueil

            # déconnexion
            logout:
                path: logout
                target: /  # après logout, retour page accueil

    # ---------------- ACCESS CONTROL ----------------
    access_control:
        # admin seulement sur /admin
        - { path: ^/admin, roles: ROLE_ADMIN }

        # personnel agence sur /staff
        - { path: ^/staff, roles: ROLE_USER }

        # toutes autres pages accessibles sans login (ex: /)
        # rien à mettre => accessible à tous

# ---------------- TEST ENV ----------------
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10