# config/routes.yaml

# Chargement automatique des contrôleurs (inclut SecurityController)
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute